### ISSUE TITLE
upgrade to go 1.8 and use of go.mod files

### ISSUE THREAD

**Issue by gedw99** [ajstarks/deck#11]
I am having working on extending the code.

One reason is the fact that we are not using the go work functionality for golang 1.8.
It allows module overrides that are private.  It also ensures that the go.mod does not need any replace directives.
here is a simple example : https://github.com/xmlking/go-workspace

---

Also 2nd thing is that deck/generate has its own go.mod.   Having go.mods inside go.mods recursively like this screws up the gopls for vscode for me. vscode Workspaces does not help either.

**Comment by gedw99** [comment]
Down in the generate folder, is there any reason why we cant remove its go.mod ?

**Comment by ajstarks** [comment]
do you mean go 1.18?

**Comment by gedw99** [comment]
sorry -  yes i mean go 1.18.
