### ISSUE TITLE
Sigupin gcdeck

### ISSUE THREAD

**Issue by gedw99** [ajstarks/deck#18]
https://github.com/ajstarks/deck/blob/master/cmd/gcdeck/gcdeck.go#L593
 
Is making my wasm build fail.
Does not like sigup :)

Any many reason this being there ? I guess to a dämm killing it ?  

If you let me know it will help me decide what to do as I run this as a gui on the web as wasm.

**Comment by ajstarks** [comment]
the signal is used to refresh when seen. It can be removed.

**Comment by gedw99** [comment]
we can use conditional compilation - aka golang build tags if you want. So then it works in wasm and non wasm.

then it does not need to be removed.

if you want a PR let me know ..
