### ISSUE TITLE
pdfdeck: open times.json: no such file or directory

### ISSUE THREAD

**Issue by maigl** [ajstarks/deck#3]
pdfdeck gives me an error. It seems that some font files missing, do I have to specify the fonts somewhere? Anyway .. sometimes helvetica is missing and sometimes courier .. 

    maigl@dreggnbox:~/devel/deck_test$ pdfdeck countdown.xml 
    pdfdeck: open courier.json: no such file or directory
    maigl@dreggnbox:~/devel/deck_test$ pdfdeck countdown.xml 
    pdfdeck: open helvetica.json: no such file or directory
    
I pulled from master (commit e8d99804cbf0e4b2cd8fc27a737fa33911f09130) and used your countdown example .. and with svgdeck I get the expected results .. 

Eventhough pdfdeck fails, there is an empty result-file 'countdown.pdf'  in my folder.

**Comment by ajstarks** [comment]
You must either 1) use the -fontdir flag to specify where the fonts are (the default fonts are in $GOPATH/src/github.com/jung-kurt/gofpdf/font or 2) set the DECKFONTS environment variable to point to where to store the fonts.

**Comment by ajstarks** [comment]
Also, it's useful to use the  'makefont' utility to create your own private font directory with your custom fonts generated from TrueType (.ttf) fonts.

For example:
```
$ mkdir $HOME/Library/deckfonts
$ export DECKFONTS=$HOME/Library/deckfonts
$ cp $GOPATH/src/github.com/jung-kurt/gofpdf/font $DECKFONTS
$ cd $DECKFONTS
$ makefont -embed /path/to/file.ttf
```
Now you can run pdfdeck without specifying -fontdir
