### ISSUE TITLE
Any plan to add a table support 

### ISSUE THREAD

**Issue by ysaakpr** [ajstarks/deck#4]
Hello, I was experimenting this library, found useful, are you planning for any table support like list you provided, and whats the future roadmap on this library ? Is there any active development happening?

**Comment by ajstarks** [comment]
You can do tables by making parallel lists.  
Each item in the list are rows, and each column in the table is a separate list, and you vary the x-coordinate to place the columns.

See: https://github.com/ajstarks/deck/blob/master/examples/deck.xml and the slide with the heading "Deck Web API" for an example.

More over you can use the deck/generate package to build your own support if this is not sufficient
