### ISSUE TITLE
Rename the server command line tool

### ISSUE THREAD

**Issue by kyleconroy** [ajstarks/deck#6]
`sex` seems like a poor choice for a command line tool name. May I suggest something less suggestive? Maybe `deck-srv` or `deckapi` or `decks`?

**Comment by ajstarks** [comment]
yes, I need a better name "sex == slide execution"

**Comment by dysolution** [comment]
If it could be considered a server _daemon,_ maybe one of these could be useful:

- `deckd`
- `slided`

**Comment by ajstarks** [comment]
renamed to deckd
