### ISSUE TITLE
makefont installation?

### ISSUE THREAD

**Issue by SantoshSrinivas79** [ajstarks/deck#7]
Greeting! I am trying out this package and having trouble figuring out how to install `makefont`

I tried installing `gofpdf` but that doesn't seem to help.

`go version go1.13.5 darwin/amd64`

Thank you!

**Comment by ajstarks** [comment]
You don't really need the makefont utility for fonts but you should should choose a directory for your fonts, say $HOME/deckfonts, and set the DECKFONTS environment variable to this directory.  

Also, make sure you have the standard fonts installed from the gofpdf package: (these instructions assume you installed gofpdf in your GOPATH.)

```
$ mkdir $HOME/deckfonts # make the DECKFONTS directory
$ export DECKFONTS=$HOME/deckfonts # you should make this permanent in your shell startup
$ cp $GOPATH/src/github.com/jung-kurt/gofpdf/font/*.json $DECKFONTS
$ ls $DECKFONTS
calligra.json   DejaVuSansCondensed-BoldOblique.ttf  helvetica_1251.json  helvetica.json  zapfdingbats.json
courierbi.json  DejaVuSansCondensed-Bold.ttf         helvetica_1253.json  timesbi.json
courierb.json   DejaVuSansCondensed.json             helveticabi.json     timesb.json
courieri.json   DejaVuSansCondensed-Oblique.ttf      helveticab.json      timesi.json
courier.json    DejaVuSansCondensed.ttf              helveticai.json      times.json

```
In general you can just put TTF files obtained from anywhere in your DECKFONTS directory and then you can use them with pdfdeck:  For example, the gofpdf package has DejaVu fonts:

```
$ cp $GOPATH/src/github.com/jung-kurt/gofpdf/font/DejaVu*.ttf $DECKFONTS
$ pdfdeck -sans DejaVuSansCondensed foo.xml
```

**Comment by ajstarks** [comment]
I have updated the documentation on using DECKFONTS 
see also: https://github.com/ajstarks/deck/tree/master/cmd/pdfdeck

**Comment by ajstarks** [comment]
Updated the deckfonts repo at https://github.com/ajstarks/deckfonts

**Comment by SantoshSrinivas79** [comment]
Thank you!
