### ISSUE TITLE
Go module definitions, more package APIs

### ISSUE THREAD

**Issue by vsivsi** [ajstarks/deck#8]
Hi, I'm super excited to have found this excellent project!

A couple of quick things:

1. It would be great if both the base `deck` and `generate` packages had go module definitions.
2. All of the command line tools (especially `decksh`, `dchart` and the export tools e.g. `svgdeck`) are excellent. I just wish they each had exported golang package APIs (with module definitions) so that it was possible to build on top of all of this great work you've done in a platform independent way without relying on external command line dependencies.

Specifically, I'd *love* to be able to go from data to writing (or serving) an SVG slide/chart in a self-contained statically-linked go program, without resorting to piping together `exec.Command("dchart",...)` type code (with the attendant brittleness of depending on those execs being correctly installed, in the path, etc.)

Item 1 above is easy.  Item 2 is obviously more work, but doing it would also make it much easier to maintain those command line tools over time by abstracting the core functionality of each away from the command line processing parts.

Anyway, I'm sure you know all of this, but I can imagine so many uses for all of the hard work you've done here, if only it was a little easier to access from golang itself!

**Comment by ajstarks** [comment]
Thanks, @vsivsi.  I plan to add the go module items.  
So that I'm clear, would having dchart, svgdeck, pdfdeck, decksh, etc. as packages work for you?

**Comment by vsivsi** [comment]
I think so. Here's a specific example I was looking at today for `svgdeck`:

Inside of `svgdeck.go` is an unexported function `svgslide`
https://github.com/ajstarks/deck/blob/master/cmd/svgdeck/svgdeck.go#L383

`func svgslide(...) {}` does a lot of great work, converting a single slide in a deck struct to an SVG output stream or buffer. This one core function (and all of its lower level dependencies) have nothing in particular to do with all of the command line option processing, filename munging and I/O performed by `svgdeck`.  I think it would be totally useful to promote svgslide to its own independent sub-module with appropriate exports, etc., and then change the implementation of `svgdeck` to use that package. In that case `svgdeck` becomes a lot simpler because the functionality of svgslide is abstracted away, and svgslide potentially becomes a lot more useful because other go programs can use it directly without depending on an `svgdeck` executable being installed and in the path someplace.

Of course, this would also be an opportunity to think hard about the design of the newly exported package API (since you'd be commiting to it) and to perhaps write unit tests against it as well.

RInse and repeat for the other useful tools, especially `decksh` and `dchart`, but others as well. This is no small endeavor, but it would really amplify the programmatic usefulness of all of this great functionality you've implemented here, and I think it would make you life easier in the long run as well in maintainability, etc.

I hope that makes this issue a little clearer.

**Comment by ajstarks** [comment]
Thanks, that makes sense.  Every client (svgdeck, pdfdeck, pngdeck, fcdeck, vgdeck) has a very similar function to walk the slide structure and make content. I'm not sure if I can have a unified API for this, but turning this into a package would be first step.

I can see how decksh and dchart could be "packagized".

**Comment by ajstarks** [comment]
decksh is now a package:  

```
import  "github.com/ajstarks/decksh"
```
There is a single method:

```
// Process reads input, parses, dispatches functions for code generation
func Process(w io.Writer, r io.Reader) error
```

Included in the package is a ```decksh``` client.

**Comment by vsivsi** [comment]
Sweet. How does decksh handle its dependency on `dchart`?

**Comment by ajstarks** [comment]
currently no change.  It still needs to find it in its path.

**Comment by ajstarks** [comment]
dchart is now a Go package, includes the dchart command which should works exactly as the standalone command.  

Note that the API may change.  Please check if it works for your use-case.

**Comment by ajstarks** [comment]
dchart is now a package

```import "github.com/ajstarks/dchart"```

includes a ```dchart``` command built with the new package.

**Comment by ajstarks** [comment]
The decksh library and command now handles chart functions using the dchart library, no longer exec-ing the dchart command.

**Comment by vsivsi** [comment]
This is great. I've been using Marp to make PDF presentations using markdown (sometimes automated reports too). Given that my work is pretty much all in Go at the moment, it will be cool to try out generating presentation slides automatically from various analyses. I'll let you know how it goes!

**Comment by ajstarks** [comment]
I also have an experimental dchart library (not ready yet), which exports many more methods:

```github.com/ajstarks/dchart2```

**Comment by ajstarks** [comment]
using modules now, dchart is a library
